{% set name = "babeltrace" %}
{% set version = "2.0.0" %}

package:
  name: babeltrace
  version: {{ version }}

source:
  url: https://www.efficios.com/files/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: 4511441d98066fdfa00668f1c46036cc81c4582e3802cf861aab5e60960ebfde

build:
  number: 0
  skip: true  # [not linux or py>=310]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - automake
    - libtool
    - gnuconfig
    - make
  host:
    - pkg-config
    - python
    - swig
    - glib
    - popt
    - elfutils  # [linux]
    - libuuid  # [linux]
  run:
    - {{ pin_compatible("glib") }}
    - python

test:
  commands:
    - test -f ${PREFIX}/lib/libbabeltrace${SHLIB_EXT}


about:
  home: https://babeltrace.org/
  summary: Babeltrace, an EfficiOS project, is an open-source trace manipulation toolkit.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - TobiasFischer
